-- ============================================================
-- Home page CMS schema
-- Run: mysql -u root vkulkarni-react < schema_home.sql
-- ============================================================

USE `vkulkarni-react`;

CREATE TABLE IF NOT EXISTS home_hero (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  mantra      TEXT,
  eyebrow     VARCHAR(300) NOT NULL DEFAULT '',
  title_line1 VARCHAR(200) NOT NULL DEFAULT '',
  title_em    VARCHAR(200) NOT NULL DEFAULT '',
  title_line3 VARCHAR(200) NOT NULL DEFAULT '',
  subtitle    TEXT,
  cta1_text   VARCHAR(100) NOT NULL DEFAULT '',
  cta1_link   VARCHAR(300) NOT NULL DEFAULT '',
  cta2_text   VARCHAR(100) NOT NULL DEFAULT '',
  cta2_link   VARCHAR(300) NOT NULL DEFAULT '',
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_marquee_items (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item_text  VARCHAR(200) NOT NULL DEFAULT '',
  sort_order TINYINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_about (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  heading1   VARCHAR(200) NOT NULL DEFAULT '',
  heading_em VARCHAR(200) NOT NULL DEFAULT '',
  heading2   VARCHAR(200) NOT NULL DEFAULT '',
  bio        TEXT,
  quote      TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_about_tags (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tag_text   VARCHAR(200) NOT NULL DEFAULT '',
  sort_order TINYINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_articles (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  featured   TINYINT(1) NOT NULL DEFAULT 0,
  category   VARCHAR(200) NOT NULL DEFAULT '',
  title      VARCHAR(500) NOT NULL DEFAULT '',
  excerpt    TEXT,
  pub_date   VARCHAR(100) NOT NULL DEFAULT '',
  url        VARCHAR(1000) NOT NULL DEFAULT '',
  image_url  VARCHAR(1000) DEFAULT NULL,
  sort_order TINYINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_themes (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  theme_key   VARCHAR(50)  NOT NULL DEFAULT '',
  devanagari  VARCHAR(50)  NOT NULL DEFAULT '',
  name        VARCHAR(200) NOT NULL DEFAULT '',
  description TEXT,
  count       SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  sort_order  TINYINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_quote (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quote_text     TEXT,
  quote_attr     VARCHAR(300) NOT NULL DEFAULT '',
  quote_mark_url VARCHAR(1000) NOT NULL DEFAULT '',
  ornament_url   VARCHAR(1000) NOT NULL DEFAULT '',
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_talks (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  label      VARCHAR(100) NOT NULL DEFAULT '',
  title      VARCHAR(500) NOT NULL DEFAULT '',
  youtube_id VARCHAR(50)  NOT NULL DEFAULT '',
  thumb_url  VARCHAR(1000) DEFAULT NULL,
  sort_order TINYINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_connect (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  description TEXT,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_connect_links (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  href       VARCHAR(500) NOT NULL DEFAULT '',
  icon       VARCHAR(30)  NOT NULL DEFAULT '',
  label      VARCHAR(200) NOT NULL DEFAULT '',
  sort_order TINYINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
